# vim:fileencoding=utf-8:foldmethod=marker

font_family JetBrainsMono NF
font_size 10.0
map ctrl+c  copy_to_clipboard
map ctrl+v  paste_from_clipboard
background_opacity 0.8
dynamic_background_opacity yes
window_margin_width 10
window_padding_width 0

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
