color0 #494458
color1 #ffb4ab
color2 #96ccff
color3 #9bcbfb
color4 #cebdfe
color5 #96ccff
color6 #9bcbfb
color7 #e7e0ef
color8 #948da4
color9 #ffb4ab
color10 #96ccff
color11 #9bcbfb
color12 #cebdfe
color13 #96ccff
color14 #9bcbfb
color15 #e7e0ef

cursor                #e7e0ef
cursor_text_color     #14121c
background            #14121c
foreground            #e7e0ef
selection_foreground  #cbc3dc
selection_background  #494458
active_border_color   #96ccff
inactive_border_color #494458
url_color             #96ccff

active_tab_foreground   #003353
active_tab_background   #96ccff
inactive_tab_foreground #cbc3dc
inactive_tab_background #494458
cursor_trail_color      #cbc3dc
